name: Create RevealPack Release From Tag

on:
  push:
    tags:
      - 'v*.*.*' 

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write permissions for contents

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Check the built package
        run: twine check dist/*

      - name: Debug - List files in dist directory
        run: ls -la dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
