name: Create RevealPack Release From Tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/RevealPack
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build Docs
        run: poetry run mkdocs build

      - name: Build the package
        run: poetry build

      - name: Check the built package
        run: poetry run twine check dist/*

      - name: List built package contents
        run: tar -tzf dist/*.tar.gz

      - name: Publish RevealPack to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Get tag message
        id: tag_message
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_MESSAGE<<EOF" >> $GITHUB_ENV
          git tag -l --format='%(contents:subject)%0a%0a%(contents:body)' $TAG_NAME >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          body: ${{ env.TAG_MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
